Move GitHub ribbon to the right
ocsf/ocsf-server pull request #67
Opened 2024-02-19 16:00 UTC by lukas-krecan-s1

We currently have many extensions and profiles and the ribbon gets  in the way. As it's not possible to scroll the left panel, it's hard to click on an extension.

<img width="200" alt="Screenshot 2024-01-17 at 15 28 31" src="https://github.com/ocsf/ocsf-server/assets/146833112/87c4869a-2246-4295-8b16-2c5434da946f">

2024-02-20 22:57 UTC, rmouritzen-splunk requested changes

2024-02-20 22:57 UTC, rmouritzen-splunk commented on priv/static/css/app.css
I like this, though I'd add a bit more. First, the GitHub ribbon doesn't follow the bottom of the page when resizing. Second, the ribbon covers the footer, which has (probably) important information, so the ribbon should be behind it in z-order, plus moved up a bit.

The first change is at line 139, changing the position from `absolute` to `fixed`:
```
  .github-ribbon {
    position: fixed;
```

The second is at line 161, moving the ribbon up a bit, changing the `bottom` from `45px` to `60px`.
```
  .github-ribbon a {
    .
    .
    .
    bottom: 60px;
  }
```

The last change sets the footer's z-order to 2 so it stays on top of the ribbon, which uses 1. This adds a new line at 244, setting `z-index: 2;`.
```
/* Custom page footer */
.footer {
  z-index: 2;
  position: fixed;
  .
  .
  .
```

2024-02-21 13:44 UTC, lukas-krecan-s1 commented on priv/static/css/app.css
Done, thanks

2024-02-22 20:27 UTC, floydtree approved these changes
Looks good, thanks!

2024-02-22 22:42 UTC, rmouritzen-splunk approved these changes

2024-02-22 22:42 UTC, merged